### ISSUE TITLE
HTTP Basic Auth not working on endpoints authenticated against spMiddleware.authenticate

### ISSUE THREAD

**Issue by javierbq** [stormpath/stormpath-sdk-express#14]
I am trying to authenticate using simple auth and I get the following error.

```

/Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/lib/MiddlewareContext.js:141
      if(token===req.accessToken.body.xsrfToken){
                                ^

TypeError: Cannot read property 'body' of undefined
    at MiddlewareContext.xsrfValidator (/Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/lib/MiddlewareContext.js:141:33)
    at /Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/lib/middleware/authenticateBasicAuth.js:20:11
    at Object.wrapGetResourceResponse [as _wrapGetResourceResponse] (/Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/node_modules/stormpath/lib/ds/DataStore.js:88:12)
    at onCacheResult (/Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/node_modules/stormpath/lib/ds/DataStore.js:295:13)
    at /Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/node_modules/stormpath/lib/cache/Cache.js:73:12
    at MemoryStore.get (/Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/node_modules/stormpath/lib/cache/MemoryStore.js:8:12)
    at Cache.get (/Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/node_modules/stormpath/lib/cache/Cache.js:52:14)
    at CacheHandler.getCachedResource [as get] (/Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/node_modules/stormpath/lib/cache/CacheHandler.js:91:51)
    at Object.executeRequest [as exec] (/Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/node_modules/stormpath/lib/ds/DataStore.js:293:22)
    at Object.getResource (/Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/node_modules/stormpath/lib/ds/DataStore.js:121:16)
    at AuthenticationResult.getAuthenticationResultAccount [as getAccount] (/Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/node_modules/stormpath/lib/resource/AuthenticationResult.js:20:25)
    at /Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/lib/middleware/authenticateBasicAuth.js:15:28
    at /Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/node_modules/stormpath/lib/authc/BasicApiAuthenticator.js:28:9
    at /Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/node_modules/stormpath/lib/resource/Application.js:269:7
    at /Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/node_modules/stormpath/lib/ds/DataStore.js:84:7
    at /Users/javier/projects/cyrus-cad/node_modules/stormpath-sdk-express/node_modules/stormpath/node_modules/async/lib/async.js:240:13
```

**Comment by robertjd** [comment]
Hi @javierbq , I just wanted to verify that you found a resolution for this problem?
