### ISSUE TITLE
throw new Error('invalid spConfig - cann\'t construct a client');

### ISSUE THREAD

**Issue by ashishbajaj99** [stormpath/stormpath-sdk-express#3]
I am getting the following error when I am integrating the following code in:

```
var stormpathSdkExpress = require('stormpath-sdk-express');

// Create Stormpath Middleware
var spMiddleware = stormpathSdkExpress.createMiddleware({
  accessTokenTtl: 60 * 60 * 24 // One day (24 hours)
});
```

What do you think is the problem? From my package.json, here is the version of the module that I have in my server code: "stormpath-sdk-express": "^0.4.3"

```
node_modules/stormpath-sdk-express/lib/MiddlewareContext.js:66
    throw new Error('invalid spConfig - cann\'t construct a client');
          ^
Error: invalid spConfig - cann't construct a client
    at new MiddlewareContext (/Users/shriya/ashish/node_tutorial/jwt-stormpath/node_modules/stormpath-sdk-express/lib/MiddlewareContext.js:66:11)
    at Object.createMiddleware (/Users/shriya/ashish/node_tutorial/jwt-stormpath/node_modules/stormpath-sdk-express/index.js:51:17)
    at Object.<anonymous> (/Users/shriya/ashish/node_tutorial/jwt-stormpath/server/routes.js:11:40)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/shriya/ashish/node_tutorial/jwt-stormpath/server/app.js:16:1)
```

**Comment by ashishbajaj99** [comment]
Rookie error, needed a complete server restart to pick up the environment variables. Sorry for the trouble.

**Comment by robertjd** [comment]
Hey, I'm glad to hear it's working now!  The error message I'm sending is pretty lame, I've made a note to fix it and make it more descriptive :)

**Comment by ashishbajaj99** [comment]
Thanks Robert!

**Comment by robertjd** [comment]
Happy to help!  FYI, I've just pushed a new version which has better error handling for this situation :)

**Comment by ashishbajaj99** [comment]
Cool, thanks, just picked it up
