### ISSUE TITLE
Using groupsRequired middleware isn't working, not allowing Express to start

### ISSUE THREAD

**Issue by danscrima** [stormpath/stormpath-sdk-express#7]
What I'm experiencing in my project is the same as I'm seeing in the angular example app at https://github.com/stormpath/stormpath-sdk-angularjs/tree/master/example/dashboard-app

If you change the line:

``` javascript
app.use('/api/things', spMiddleware.authenticate, require('./api/thing'));
```

to

``` javascript
app.use('/api/things', spMiddleware.groupsRequired(['admins']), require('./api/thing'));
```

then it blows up with this error

```
TypeError: Cannot read property 'host' of undefined
    at MiddlewareContext.corsHandler (/home/dscrima/dashboard-app/node_modules/stormpath-sdk-express/lib/middleware/corsHandler.js:9:24)
    at Function.corsPrefilter [as groupsRequired] (/home/dscrima/dashboard-app/node_modules/stormpath-sdk-express/index.js:81:25)
    at module.exports (/home/dscrima/dashboard-app/server/routes.js:17:39)
    at Object.<anonymous> (/home/dscrima/dashboard-app/server/app.js:16:20)
```

Not sure why at this point in the express workflow that req.headers is undefined, but it's not allowing access control, or even allowing the express server to start. 

Thanks!

**Comment by robertjd** [comment]
Hi @danscrima 

This was a bug, thanks for finding!  I just published a fix as version `0.4.9` - can you upgrade and give it a try?

Thanks!

**Comment by danscrima** [comment]
Awesome that definitely worked! Thanks so much!

**Comment by robertjd** [comment]
No prob!
